Gclass.create(:class_id => '6a')
Gclass.create(:class_id => '9b')
Gclass.create(:class_id => '7c')
Gclass.create(:class_id => '10a')

Subject.create(:subject_id => 'History')
Subject.create(:subject_id => 'Math')
Subject.create(:subject_id => 'Soft eng')
Subject.create(:subject_id => 'Geo')
Subject.create(:subject_id => 'Calculus')
